spring.application.name=rp-gate-backend
server.address=127.0.0.1
server.port=8081
spring.datasource.url=jdbc:sqlite:${user.dir}/../database/rp_gate.db
rp.gate.database-path=${user.dir}/../database/rp_gate.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON
spring.sql.init.mode=never
spring.jackson.default-property-inclusion=non_null
server.error.include-message=never
