const BASE_URL = 'http://127.0.0.1:8081/api';
const timeoutMs = 8000;
function messageFor(status, body) { if (status === 0) return 'Backend unavailable. Start the local Java server and try again.'; if (status === 400) return body?.message || 'The server rejected the entered data. Check the required fields.'; if (status === 409) return body?.message || 'This record already exists or conflicts with existing data.'; if (status === 404) return body?.message || 'The requested record was not found.'; if (status >= 500) return body?.message || 'The local database reported an error.'; return body?.message || `Backend request failed (${status}).`; }
async function request(path, options = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(`${BASE_URL}${path}`, { ...options, signal: controller.signal, headers: { Accept: 'application/json', ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}) } }); const text = await response.text(); let body = null; try { body = text ? JSON.parse(text) : null; } catch { throw new Error('The backend returned an invalid response.'); } if (!response.ok) throw new Error(messageFor(response.status, body)); return body; } catch (error) { if (error.name === 'AbortError') throw new Error('The backend request timed out.'); if (error instanceof TypeError) throw new Error('Backend unavailable. Start the local Java server and try again.'); throw error; } finally { clearTimeout(timer); } }
async function requestBinary(path) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(`${BASE_URL}${path}`, { signal:controller.signal, headers:{Accept:'application/vnd.sqlite3'} }); if (!response.ok) { let body=null; try { body=await response.json(); } catch {} throw new Error(messageFor(response.status,body)); } return response.blob(); } catch(error) { if(error.name==='AbortError') throw new Error('The backend request timed out.'); if(error instanceof TypeError) throw new Error('Backend unavailable. Start the local Java server and try again.'); throw error; } finally { clearTimeout(timer); } }
const query = (params) => { const value = new URLSearchParams(); Object.entries(params).forEach(([key, item]) => { if (item !== undefined && item !== null && item !== '') value.set(key, item); }); const text = value.toString(); return text ? `?${text}` : ''; };
const clean = (value) => value?.trim() || null;
const personFromData = (data) => ({ personnelId: null, armyNo: clean(data.leave_army || data.td_army || data.veh_army || data.out_id || data.night_id), cardNo: clean(data.leave_card || data.td_card || data.veh_card || data.out_card || data.night_card), rank: clean(data.leave_rank || data.td_rank || data.veh_rank || data.out_rank || data.night_rank), name: clean(data.leave_name || data.td_name || data.veh_name || data.night_name), mobileNo: clean(data.leave_mobile), unit: clean(data.td_unit) });
const movementDetails = (category, data) => ({ Leave:{leave_type:data.leave_type,destination_from:data.leave_dest,mobile_no:data.leave_mobile}, 'TD / Posting':{movement_subtype:data.td_type,unit_formation:data.td_unit,authority_order_no:data.td_order,destination:data.td_dest}, 'Vehicle In / Out':{vehicle_no:data.veh_no,vehicle_type:data.veh_type,driver_name:data.veh_name,purpose:data.veh_purpose}, Outpass:{pass_no:data.out_pass,time_out:data.out_dt,expected_return:data.out_return,purpose_destination:data.out_purpose}, 'Night Pass':{pass_no:data.night_pass,time_out:data.night_dt,return_time:data.night_return,destination:data.night_dest} }[category]);
const categoryValue = (category) => ({Leave:'LEAVE','TD / Posting':'TD_POSTING','Vehicle In / Out':'VEHICLE',Outpass:'OUTPASS','Night Pass':'NIGHT_PASS'}[category]);
const movementType = (category, data) => category === 'Leave' ? data.leave_move : category === 'TD / Posting' ? data.td_type : category === 'Vehicle In / Out' ? data.veh_move : null;
const movementAt = (category, data) => ({Leave:data.leave_dt,'TD / Posting':data.td_dt,'Vehicle In / Out':data.veh_dt,Outpass:data.out_dt,'Night Pass':data.night_dt}[category] || new Date().toISOString());
export const api = {
  loadPeople: (search = '') => request(`/personnel${query({ search })}`), searchPeople: (search) => request(`/personnel${query({ search })}`), createPersonnel: (data) => request('/personnel', { method:'POST', body:JSON.stringify(data) }), updatePersonnel: (id, data) => request(`/personnel/${id}`, { method:'PUT', body:JSON.stringify(data) }), deletePersonnel: (id) => request(`/personnel/${id}`, { method:'DELETE' }), clearPersonnel: () => request('/personnel', { method:'DELETE' }),
  loadRecords: (filters = {}) => request(`/movements${query({ ...filters, category:filters.category ? categoryValue(filters.category) : undefined })}`), getRecord: (id) => request(`/movements/${id}`), saveMovement: (category, data) => request('/movements', { method:'POST', body:JSON.stringify({category:categoryValue(category),movementAt:movementAt(category,data),movementType:movementType(category,data),remarks:data.leave_remark || data.td_remark || data.veh_remark || data.out_remark || data.night_remark || null,person:personFromData(data),details:movementDetails(category,data)}) }), updateMovement: (id, category, data) => request(`/movements/${id}`, { method:'PUT', body:JSON.stringify({category:categoryValue(category),movementAt:movementAt(category,data),movementType:movementType(category,data),remarks:data.leave_remark || data.td_remark || data.veh_remark || data.out_remark || data.night_remark || null,person:personFromData(data),details:movementDetails(category,data)}) }), deleteRecord: (id) => request(`/movements/${id}`, { method:'DELETE' }), deleteAllRecords: () => request('/movements', { method:'DELETE' }),
  dailyReport: (date) => request(`/reports/daily${query({ date })}`), categoryReport: (from, to) => request(`/reports/category-summary${query({ from, to })}`), dashboardSummary: () => request('/reports/dashboard'), personnelReport: (id) => request(`/reports/personnel/${id}`), exportBackup: () => request('/backup'), downloadDatabaseBackup: () => requestBinary('/backup/database'), validateBackup: (file) => { const form = new FormData(); form.append('file', file); return request('/backup/validate-database', { method:'POST', body:form }); }, importBackup: (file) => { const form = new FormData(); form.append('file', file); return request('/backup/restore-database', { method:'POST', body:form }); }
};
export { BASE_URL };
