import { state, replacePeople, replaceRecords } from './state.js'; import { api } from './api.js'; import { norm, esc, val } from './utils.js'; import { page, setFilter } from './navigation.js'; import { findPerson, autoFill, quickFill } from './autofill.js'; import { renderRecent, renderRecords, refreshRecords, saveForm, clearPage, summary, deleteAll, resetForm } from './records.js'; import { updateList, renderPersonnel, clearPersonnel, downloadPersonnel, refreshPeople } from './personnel.js'; import { dailyReport, categoryReport, personReport } from './reports.js'; import { downloadCSV, downloadBackup, uploadBackup, uploadPersonnel, downloadRows } from './backup.js'; import { printRecord, printAll, printCurrentForm, printReport } from './print.js';
export async function render() { try { const summary=await api.dashboardSummary(); document.getElementById('sTotal').textContent=summary.total; document.getElementById('sToday').textContent=summary.today; document.getElementById('sIn').textContent=summary.in; document.getElementById('sOut').textContent=summary.out; document.getElementById('sPeople').textContent=summary.personnel; updateList(); renderRecent(); } catch (error) { window.RPGate.showError(error); } }
window.RPGate = { state, norm, esc, val, render, renderRecords, renderPersonnel, renderHistory: () => {}, summary, dailyReport, downloadRows, resetForm, refreshPeople, refreshRecords, showError: (error) => alert(error.message || 'The backend request failed.') };
Object.assign(window, { page, setFilter, findPerson, autoFill, quickFill, saveForm, clearPage, deleteAll, clearPersonnel, downloadPersonnel, downloadCSV, downloadBackup, uploadBackup, uploadPersonnel, printRecord, printAll, printCurrentForm, printReport, dailyReport, categoryReport, personReport });
window.RPGate.renderHistory = async function renderHistory() { const query = val('historySearch'); const box = document.getElementById('historyBox'); if (!box) return; if (!query) { box.innerHTML = ''; return; } try { const matches = await api.searchPeople(query); if (matches.length !== 1) { box.innerHTML = matches.length ? '<div class="notice">More than one person matches. Enter a complete Army No, I-Card No, or Name.</div>' : ''; return; } const report = await api.personnelReport(matches[0].personnelId); box.innerHTML = `<div class="box"><h2>Personnel Details</h2><div class="grid"><div><b>Army No:</b> ${esc(matches[0].armyNo)}</div><div><b>I-Card:</b> ${esc(matches[0].cardNo)}</div><div><b>Rank:</b> ${esc(matches[0].rank)}</div><div><b>Name:</b> ${esc(matches[0].name)}</div><div><b>Unit:</b> ${esc(matches[0].unit)}</div><div><b>Mobile:</b> ${esc(matches[0].mobileNo)}</div></div></div><div class="box section-spaced"><h2>Movement History (${report.records.length})</h2>${reportTable(report.records)}</div>`; } catch (error) { window.RPGate.showError(error); } };
function reportTable(records) { return `<div class="tablewrap"><table><thead><tr><th>Date/Time</th><th>Category</th><th>Movement</th><th>Vehicle</th><th>Details</th></tr></thead><tbody>${records.map((record) => `<tr><td>${esc(new Date(record.movementAt).toLocaleString())}</td><td>${esc(record.category)}</td><td>${esc(record.movementType)}</td><td>${esc(record.details?.vehicle_no)}</td><td>${esc(JSON.stringify(record.details || {}))}</td></tr>`).join('')}</tbody></table></div>`; }
window.setInterval(() => { const clock=document.getElementById('clock'); if (clock) { const date=new Date(); clock.innerHTML=date.toLocaleDateString('en-GB')+'<br>'+date.toLocaleDateString('en-US',{weekday:'long'})+'<br>'+date.toLocaleTimeString(); } }, 1000);
async function initialize() { try { await refreshRecords(); render(); } catch (error) { window.RPGate.showError(error); } }
initialize();
