import { state, replacePeople } from './state.js';
import { api } from './api.js';
import { norm, esc, val } from './utils.js';
export async function refreshPeople(search = '') { try { replacePeople(await api.loadPeople(search)); updateList(); renderPersonnel(); } catch (error) { window.RPGate.showError(error); } }
export function dedupePeople(people) { const merged = []; people.forEach((person) => { const identifiers = [person.armyNo, person.cardNo, person.name].filter(Boolean).map(norm); const existing = merged.findIndex((item) => [item.armyNo, item.cardNo, item.name].filter(Boolean).map(norm).some((value) => identifiers.includes(value))); if (existing < 0) merged.push({ armyNo:person.armyNo || '', cardNo:person.cardNo || '', rank:person.rank || '', name:person.name || '', mobile:person.mobile || '', unit:person.unit || '' }); else merged[existing] = Object.fromEntries(Object.entries({ ...merged[existing], ...person }).filter(([, value]) => value !== '')); }); return merged; }
export function updateList() { const list = document.getElementById('personList'); if (list) list.innerHTML = state.people.map((person) => `<option value="${esc(person.armyNo)}">${esc(person.name)} | ${esc(person.cardNo)} | ${esc(person.rank)}</option>`).join(''); const count = document.getElementById('sPeople'); if (count) count.textContent = state.people.length; }
export function renderPersonnel() { const body = document.getElementById('personBody'); if (!body) return; const filter = norm(val('personFilter')); const people = state.people.filter((person) => !filter || norm([person.armyNo,person.cardNo,person.rank,person.name,person.mobileNo,person.unit].join(' ')).includes(filter)); body.innerHTML = people.length ? people.map((person, index) => `<tr><td>${index + 1}</td><td>${esc(person.armyNo)}</td><td>${esc(person.cardNo)}</td><td>${esc(person.rank)}</td><td>${esc(person.name)}</td><td>${esc(person.mobileNo)}</td><td>${esc(person.unit)}</td></tr>`).join('') : '<tr><td colspan="7">No personnel found.</td></tr>'; }
export async function clearPersonnel() { if (confirm('Clear Personnel Master? Movement records will remain.')) { try { await api.clearPersonnel(); replacePeople([]); updateList(); renderPersonnel(); } catch (error) { window.RPGate.showError(error); } } }
export async function downloadPersonnel() { try { const people = await api.loadPeople(); replacePeople(people); updateList(); const rows = [['Army No','I-Card No','Rank','Name','Mobile No','Unit'], ...people.map((person) => [person.armyNo,person.cardNo,person.rank,person.name,person.mobileNo,person.unit])]; window.RPGate.downloadRows(rows, 'RP_Gate_Personnel_Master.csv'); } catch (error) { window.RPGate.showError(error); } }
