import { state, replaceRecords } from './state.js';
import { api } from './api.js';
import { val, norm, esc } from './utils.js';
import { validateForm } from './validation.js';
import { leave } from './modules/leave.js'; import { tdPosting } from './modules/td-posting.js'; import { vehicle } from './modules/vehicle.js'; import { outpass } from './modules/outpass.js'; import { nightPass } from './modules/night-pass.js';
const modules = { Leave:leave, 'TD / Posting':tdPosting, 'Vehicle In / Out':vehicle, Outpass:outpass, 'Night Pass':nightPass };
export function summary(record) { const data = record.data || record.details || {}; const person = record.person || {}; return { id:data.leave_army || data.td_army || data.veh_army || data.out_id || data.night_id || data.veh_no || data.vehicleNo || data.vehicle_no || person.armyNo || '', card:data.leave_card || data.td_card || data.veh_card || data.out_card || data.night_card || person.cardNo || '', name:data.leave_name || data.td_name || data.night_name || data.out_name || data.veh_name || data.driver_name || person.name || '', move:data.leave_move || data.td_type || data.veh_move || record.movementType || '', vehicle:data.veh_no || data.vehicleNo || data.vehicle_no || '', dt:data.leave_dt || data.td_dt || data.veh_dt || data.out_dt || data.night_dt || data.time_out || record.movementAt || record.createdAt || record.created, details:Object.entries(data).filter((entry) => entry[1]).map((entry) => `${entry[0]}: ${entry[1]}`).join(' | ') }; }
export async function saveForm(moduleName) { const definition = modules[moduleName]; if (!definition || state.lastSave?.module === moduleName && Date.now() - state.lastSave.time < 1500) return; const data = Object.fromEntries(definition.fields.map((id) => [id, val(id).trim()])); if (!validateForm(moduleName, data)) return; const signature = JSON.stringify([moduleName, data]); if (state.lastSave?.signature === signature && Date.now() - state.lastSave.time < 10000) return; state.lastSave = { module:moduleName, signature, time:Date.now() }; try { await api.saveMovement(moduleName, data); clearPage(definition.pageId); alert(`${moduleName} record saved successfully.`); await window.RPGate.refreshPeople(); await window.RPGate.refreshRecords(); } catch (error) { state.lastSave = null; window.RPGate.showError(error); } }
export function clearPage(id) { document.querySelectorAll(`#${id} input, #${id} textarea`).forEach((element) => { element.value = ''; delete element.dataset.autofilled; delete element.dataset.autofillValue; element.classList.remove('autofill'); }); document.querySelectorAll(`#${id} select`).forEach((element) => { element.selectedIndex = 0; }); }
export function resetLeaveForm() { clearPage('leave'); }
export function resetTDForm() { clearPage('td'); }
export function resetVehicleForm() { clearPage('vehicle'); }
export function resetOutpassForm() { clearPage('outpass'); }
export function resetNightPassForm() { clearPage('night'); }
export function resetForm(id) { ({ leave:resetLeaveForm, td:resetTDForm, vehicle:resetVehicleForm, outpass:resetOutpassForm, night:resetNightPassForm }[id] || (() => {}))(); }
export function renderRecent() { const body = document.getElementById('recentBody'); if (!body) return; body.innerHTML = state.records.slice(-8).reverse().map((record, index) => { const item = summary(record); return `<tr><td>${index + 1}</td><td>${esc(new Date(item.dt).toLocaleString())}</td><td>${esc(record.category || record.module)}</td><td>${esc(item.name)}</td><td>${esc(item.id || item.card)}</td><td>${esc(item.move)}</td><td>${esc(item.details.slice(0,90))}</td><td><button class="smallbtn no-print" onclick="printRecord(${record.movementId || record.id})">🖨</button></td></tr>`; }).join(''); }
function renderRows() { const body = document.getElementById('recordBody'); if (!body) return; body.innerHTML = state.records.length ? state.records.slice().reverse().map((record, index) => { const item = summary(record); return `<tr><td>${index + 1}</td><td>${esc(new Date(item.dt).toLocaleString())}</td><td>${esc(record.category || record.module)}</td><td>${esc(item.id)}</td><td>${esc(item.name)}</td><td>${esc(item.move)}</td><td>${esc(item.vehicle)}</td><td>${esc(item.details)}</td><td class="no-print"><button class="smallbtn" onclick="printRecord(${record.movementId || record.id})">🖨</button></td></tr>`; }).join('') : '<tr><td colspan="9">No movement records found.</td></tr>'; }
export async function refreshRecords(filters = {}) { try { replaceRecords(await api.loadRecords(filters)); renderRows(); renderRecent(); } catch (error) { window.RPGate.showError(error); } }
export async function renderRecords() { const filter = norm(val('recordFilter')); const category = val('categoryFilter'); if (filter || category) return refreshRecords({ search:filter, category:category || undefined }); renderRows(); }
export async function deleteAll() { if (!confirm('Delete all movement records?')) return; try { await api.deleteAllRecords(); await refreshRecords(); alert('All movement records deleted.'); } catch (error) { window.RPGate.showError(error); } }
export async function deleteRecord(id) { try { await api.deleteRecord(id); await refreshRecords(); } catch (error) { window.RPGate.showError(error); } }
