package com.rpgate.repository;

import com.rpgate.dto.MovementDtos;
import com.rpgate.model.Category;
import com.rpgate.model.MovementStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.util.*;

@Repository
public class MovementRepository {
    private final JdbcTemplate db;
    public MovementRepository(JdbcTemplate db) { this.db=db; }
    public long insert(MovementDtos.Request x, MovementDtos.PersonRef p) { return db.queryForObject("INSERT INTO movement_records(personnel_id,category,movement_type,movement_at,historical_army_no,historical_card_no,historical_rank,historical_name,historical_mobile_no,historical_unit,remarks) VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING movement_id", Long.class,p==null?null:p.personnelId(),x.category().value(),x.movementType(),x.movementAt(),p==null?null:p.armyNo(),p==null?null:p.cardNo(),p==null?null:p.rank(),p==null?null:p.name(),p==null?null:p.mobileNo(),p==null?null:p.unit(),x.remarks()); }
    public void detail(long id, Category c, Map<String,String> d) { if (d==null) d=Map.of(); String sql=switch(c){case LEAVE->"INSERT INTO leave_records(movement_id,leave_type,destination_from,mobile_no) VALUES(?,?,?,?)";case TD_POSTING->"INSERT INTO td_posting_records(movement_id,movement_subtype,unit_formation,authority_order_no,destination) VALUES(?,?,?,?,?)";case VEHICLE->"INSERT INTO vehicle_records(movement_id,vehicle_no,vehicle_type,driver_personnel_id,purpose) VALUES(?,?,?,?,?)";case OUTPASS->"INSERT INTO outpass_records(movement_id,pass_no,time_out,expected_return,purpose_destination) VALUES(?,?,?,?,?)";case NIGHT_PASS->"INSERT INTO night_pass_records(movement_id,pass_no,time_out,return_time,destination) VALUES(?,?,?,?,?)";}; Object[] a=switch(c){case LEAVE->new Object[]{id,d.get("leave_type"),d.get("destination_from"),d.get("mobile_no")};case TD_POSTING->new Object[]{id,d.get("movement_subtype"),d.get("unit_formation"),d.get("authority_order_no"),d.get("destination")};case VEHICLE->new Object[]{id,d.get("vehicle_no"),d.get("vehicle_type"),d.get("driver_personnel_id"),d.get("purpose")};case OUTPASS->new Object[]{id,d.get("pass_no"),d.get("time_out"),d.get("expected_return"),d.get("purpose_destination")};case NIGHT_PASS->new Object[]{id,d.get("pass_no"),d.get("time_out"),d.get("return_time"),d.get("destination")};}; db.update(sql,a); }
    public int delete(long id){return db.update("UPDATE movement_records SET status='CANCELLED' WHERE movement_id=?",id);}
    public int deleteAll(){return db.update("UPDATE movement_records SET status='CANCELLED' WHERE status <> 'CANCELLED'");}
    public int update(long id, MovementDtos.Request x, MovementDtos.PersonRef p){int changed=db.update("UPDATE movement_records SET personnel_id=?,category=?,movement_type=?,movement_at=?,historical_army_no=?,historical_card_no=?,historical_rank=?,historical_name=?,historical_mobile_no=?,historical_unit=?,remarks=? WHERE movement_id=? AND status <> 'CANCELLED'",p.personnelId(),x.category().value(),x.movementType(),x.movementAt(),p.armyNo(),p.cardNo(),p.rank(),p.name(),p.mobileNo(),p.unit(),x.remarks(),id);if(changed>0){for(String table:List.of("leave_records","td_posting_records","vehicle_records","outpass_records","night_pass_records"))db.update("DELETE FROM "+table+" WHERE movement_id=?",id);detail(id,x.category(),x.details());}return changed;}
    public List<MovementDtos.Response> list(MovementDtos.Filter f){StringBuilder q=new StringBuilder("SELECT m.*, l.leave_type AS detail_leave_type, l.destination_from AS detail_leave_destination, l.mobile_no AS detail_leave_mobile, t.movement_subtype AS detail_td_subtype, t.unit_formation AS detail_td_unit, t.authority_order_no AS detail_td_order, t.destination AS detail_td_destination, v.vehicle_no AS detail_vehicle_no, v.vehicle_type AS detail_vehicle_type, v.purpose AS detail_vehicle_purpose, o.pass_no AS detail_out_pass, o.time_out AS detail_out_time, o.expected_return AS detail_out_return, o.purpose_destination AS detail_out_purpose, n.pass_no AS detail_night_pass, n.time_out AS detail_night_time, n.return_time AS detail_night_return, n.destination AS detail_night_destination FROM movement_records m LEFT JOIN leave_records l ON l.movement_id=m.movement_id LEFT JOIN td_posting_records t ON t.movement_id=m.movement_id LEFT JOIN vehicle_records v ON v.movement_id=m.movement_id LEFT JOIN outpass_records o ON o.movement_id=m.movement_id LEFT JOIN night_pass_records n ON n.movement_id=m.movement_id WHERE 1=1");List<Object>a=new ArrayList<>();if(f.category()!=null){q.append(" AND m.category=?");a.add(f.category().value());}if(f.movementType()!=null&&!f.movementType().isBlank()){q.append(" AND m.movement_type=?");a.add(f.movementType());}if(f.status()!=null){q.append(" AND m.status=?");a.add(f.status().name());}if(f.from()!=null){q.append(" AND m.movement_at>=?");a.add(f.from());}if(f.to()!=null){q.append(" AND m.movement_at<=?");a.add(f.to());}if(f.personnelId()!=null){q.append(" AND m.personnel_id=?");a.add(f.personnelId());}if(f.search()!=null&&!f.search().isBlank()){q.append(" AND lower(coalesce(m.historical_army_no,'')||' '||coalesce(m.historical_card_no,'')||' '||m.historical_name||' '||m.category) LIKE ?");a.add("%"+f.search().toLowerCase()+"%");}q.append(" ORDER BY m.movement_at DESC");return db.query(q.toString(),this::map,a.toArray());}
    public MovementDtos.Response get(long id){List<MovementDtos.Response>x=list(new MovementDtos.Filter(null,null,null,null,null,null,null));return x.stream().filter(r->r.movementId()==id).findFirst().orElse(null);}
    private MovementDtos.Response map(java.sql.ResultSet r,int n)throws java.sql.SQLException{Map<String,String>d=new LinkedHashMap<>();Category c=Category.fromValue(r.getString("category")); if(c==Category.LEAVE){d.put("leave_type",r.getString("detail_leave_type"));d.put("destination_from",r.getString("detail_leave_destination"));d.put("mobile_no",r.getString("detail_leave_mobile"));} if(c==Category.TD_POSTING){d.put("movement_subtype",r.getString("detail_td_subtype"));d.put("unit_formation",r.getString("detail_td_unit"));d.put("authority_order_no",r.getString("detail_td_order"));d.put("destination",r.getString("detail_td_destination"));} if(c==Category.VEHICLE){d.put("vehicle_no",r.getString("detail_vehicle_no"));d.put("vehicle_type",r.getString("detail_vehicle_type"));d.put("driver_name",r.getString("historical_name"));d.put("purpose",r.getString("detail_vehicle_purpose"));} if(c==Category.OUTPASS){d.put("pass_no",r.getString("detail_out_pass"));d.put("time_out",r.getString("detail_out_time"));d.put("expected_return",r.getString("detail_out_return"));d.put("purpose_destination",r.getString("detail_out_purpose"));} if(c==Category.NIGHT_PASS){d.put("pass_no",r.getString("detail_night_pass"));d.put("time_out",r.getString("detail_night_time"));d.put("return_time",r.getString("detail_night_return"));d.put("destination",r.getString("detail_night_destination"));} Object rawPersonnelId=r.getObject("personnel_id"); Long personnelId=rawPersonnelId instanceof Number number?number.longValue():null; return new MovementDtos.Response(r.getLong("movement_id"),c,r.getString("movement_type"),r.getString("movement_at"),r.getString("created_at"),r.getString("updated_at"),MovementStatus.valueOf(r.getString("status")),new MovementDtos.PersonRef(personnelId,r.getString("historical_army_no"),r.getString("historical_card_no"),r.getString("historical_rank"),r.getString("historical_name"),r.getString("historical_mobile_no"),r.getString("historical_unit")),d,r.getString("remarks"));}
}
